# ============================================================================
# config/training/training.yaml
# ============================================================================
# Training hyperparameters
resume_from_checkpoint: false  # Options: null | true | or specify a path like "outputs/checkpoint-500"
output_dir: code-llama-3-1-8b-text-to-sql
num_train_epochs: 3
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2e-4
max_seq_length: 2048
max_grad_norm: 1.0
warmup_ratio: 0.03
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.05
lora_r: 8
