# ============================================================================
# config/hf/hf.yaml
# ============================================================================
model_id: meta-llama/Llama-3.1-8B-Instruct
token: ${oc.env:HF_TOKEN,null}
username: chrisjcc

# Upload configuration
upload:
  # What to upload
  push_to_hub: true
  upload_adapter: true
  upload_merged: false  # Set to true to upload merged model (requires significant memory)
  upload_dataset: true

  # Repository naming
  adapter_repo_suffix: "-text-to-sql-adapter"
  merged_repo_suffix: "-text-to-sql-merged"
  dataset_repo_name: "text-to-sql-spider-dataset"

  # Model card metadata
  author_name: "Christian Contreras Campana"
  license: "apache-2.0"
  language: "en"

  # Upload options
  include_training_args: true  # Include training_args.bin for reproducibility
  commit_message: "Upload supervised-fine-tuned text-to-SQL model"
